import { AppDataSource } from '../ormconfig';
import { ObsReef } from '../entities/observatory/Reef';
import { ObsContributor } from '../entities/observatory/Contributor';
import { ObsConflict } from '../entities/observatory/Conflict';

const REEFS = [
  { id: 1, name: 'Arrecife de Puerto Morelos', state: 'Quintana Roo', ocean: 'caribbean', region: 'Sistema Arrecifal Mesoamericano (SAM)', benthicClasses: ['coral_algae', 'sand', 'seagrass'], geomorphicClasses: ['fringing', 'reef_crest', 'lagoon'], area: 9067, depthRange: [1, 25], protection: 'anp_federal', status: 'warning', liveCoralCover: 18, bleachingAlert: 'warning', speciesRichness: 36, threats: ['thermal_stress', 'sargassum', 'tourism_pressure', 'disease_outbreak'], observations: 142, lat: 20.84, lng: -86.87, description: 'Parque Nacional Arrecife de Puerto Morelos. Barrera arrecifal tipo franjeante con laguna arrecifal somera. Forma parte del SAM y enfrenta presiones combinadas de turismo, sargazo y la enfermedad de pérdida de tejido coralino (SCTLD).', hero: '/images/reefs/puerto-morelos.jpg', imageCredit: 'CONANP' },
  { id: 2, name: 'Arrecife Cozumel', state: 'Quintana Roo', ocean: 'caribbean', region: 'Sistema Arrecifal Mesoamericano (SAM)', benthicClasses: ['coral_algae', 'rock', 'sand'], geomorphicClasses: ['fringing', 'reef_slope'], area: 11988, depthRange: [3, 50], protection: 'anp_federal', status: 'alert', liveCoralCover: 15, bleachingAlert: 'alert_1', speciesRichness: 42, threats: ['thermal_stress', 'cruise_anchoring', 'tourism_pressure', 'disease_outbreak'], observations: 287, lat: 20.39, lng: -86.97, description: 'Parque Nacional Arrecifes de Cozumel. Pendiente arrecifal con corrientes intensas y alta diversidad. El anclaje de cruceros y el SCTLD han reducido la cobertura coralina viva por debajo del 20%.', hero: '/images/reefs/cozumel.jpg', imageCredit: 'CONANP / Allen Coral Atlas' },
  { id: 3, name: 'Banco Chinchorro', state: 'Quintana Roo', ocean: 'caribbean', region: 'Sistema Arrecifal Mesoamericano (SAM)', benthicClasses: ['coral_algae', 'seagrass', 'sand'], geomorphicClasses: ['lagoon', 'reef_crest', 'patch_reef'], area: 144360, depthRange: [0, 40], protection: 'anp_federal', status: 'watch', liveCoralCover: 24, bleachingAlert: 'watch', speciesRichness: 95, threats: ['thermal_stress', 'sargassum', 'overfishing'], observations: 73, lat: 18.62, lng: -87.32, description: 'Reserva de la Biosfera Banco Chinchorro. Atolón coralino con la mayor extensión arrecifal del Atlántico mexicano. Reserva de la Biosfera y sitio Ramsar; alberga ~95 especies de coral.', hero: '/images/reefs/chinchorro.jpg', imageCredit: 'CONANP' },
  { id: 4, name: 'Sistema Arrecifal Veracruzano', state: 'Veracruz', ocean: 'gulf_of_mexico', region: 'Golfo de México', benthicClasses: ['coral_algae', 'sand', 'rubble'], geomorphicClasses: ['patch_reef', 'reef_flat'], area: 65516, depthRange: [0, 48], protection: 'anp_federal', status: 'alert', liveCoralCover: 12, bleachingAlert: 'alert_1', speciesRichness: 28, threats: ['sedimentation', 'nutrient_pollution', 'coastal_development', 'oil_spill'], observations: 98, lat: 19.18, lng: -96.10, description: 'Parque Nacional Sistema Arrecifal Veracruzano (PNSAV). Conjunto de 28 arrecifes platafórmicos frente al puerto de Veracruz. Presiona el desarrollo portuario, descargas y sedimentos del río Jamapa-Cotaxtla.', hero: '/images/reefs/sav.jpg', imageCredit: 'CONABIO' },
  { id: 5, name: 'Arrecifes de Xcalak', state: 'Quintana Roo', ocean: 'caribbean', region: 'Sistema Arrecifal Mesoamericano (SAM)', benthicClasses: ['coral_algae', 'seagrass', 'sand'], geomorphicClasses: ['fringing', 'lagoon', 'back_reef'], area: 17949, depthRange: [0, 35], protection: 'anp_federal', status: 'healthy', liveCoralCover: 31, bleachingAlert: 'no_stress', speciesRichness: 52, threats: ['thermal_stress', 'sargassum'], observations: 41, lat: 18.27, lng: -87.83, description: 'Parque Nacional Arrecifes de Xcalak. Sección sur del SAM, frontera con Belice. Arrecife franjeante con baja presión turística y cobertura coralina relativamente alta.', hero: '/images/reefs/xcalak.jpg', imageCredit: 'CONANP' },
  { id: 6, name: 'Cabo Pulmo', state: 'Baja California Sur', ocean: 'pacific', region: 'Golfo de California', benthicClasses: ['coral_algae', 'rock'], geomorphicClasses: ['fringing', 'reef_slope'], area: 7111, depthRange: [3, 25], protection: 'anp_federal', status: 'healthy', liveCoralCover: 39, bleachingAlert: 'no_stress', speciesRichness: 11, threats: ['thermal_stress', 'tourism_pressure'], observations: 156, lat: 23.45, lng: -109.43, description: 'Parque Nacional Cabo Pulmo. Único arrecife coralino vivo del Pacífico oriental. Tras la veda total establecida en 1995, la biomasa se recuperó >460%. Patrimonio Mundial UNESCO.', hero: '/images/reefs/cabo-pulmo.jpg', imageCredit: 'UNESCO / CONANP' },
  { id: 7, name: 'Isla Isabel', state: 'Nayarit', ocean: 'pacific', region: 'Pacífico mexicano central', benthicClasses: ['coral_algae', 'rock'], geomorphicClasses: ['fringing', 'patch_reef'], area: 194, depthRange: [3, 30], protection: 'anp_federal', status: 'watch', liveCoralCover: 22, bleachingAlert: 'watch', speciesRichness: 9, threats: ['thermal_stress', 'overfishing'], observations: 22, lat: 21.85, lng: -105.88, description: 'Parque Nacional Isla Isabel. Isla volcánica con comunidades coralinas de Pocillopora. Sitio Ramsar y refugio de aves marinas; presiones por flota pesquera regional.', hero: '/images/reefs/isla-isabel.jpg', imageCredit: 'CONANP' },
  { id: 8, name: 'Archipiélago de Revillagigedo', state: 'Colima', ocean: 'pacific', region: 'Pacífico oriental tropical', benthicClasses: ['coral_algae', 'rock'], geomorphicClasses: ['fringing', 'reef_slope'], area: 14808780, depthRange: [0, 60], protection: 'unesco', status: 'healthy', liveCoralCover: 35, bleachingAlert: 'no_stress', speciesRichness: 18, threats: ['thermal_stress'], observations: 67, lat: 18.81, lng: -111.07, description: 'Parque Nacional Revillagigedo. La mayor reserva marina totalmente protegida de Norteamérica (148,087 km²). Patrimonio Mundial UNESCO desde 2016. Comunidades coralinas en Socorro y Clarión.', hero: '/images/reefs/revillagigedo.jpg', imageCredit: 'UNESCO / CONANP' },
  { id: 9, name: 'Arrecife Alacranes', state: 'Yucatán', ocean: 'gulf_of_mexico', region: 'Plataforma de Yucatán', benthicClasses: ['coral_algae', 'seagrass', 'sand'], geomorphicClasses: ['lagoon', 'reef_crest', 'patch_reef'], area: 33396, depthRange: [0, 30], protection: 'anp_federal', status: 'watch', liveCoralCover: 26, bleachingAlert: 'watch', speciesRichness: 25, threats: ['thermal_stress', 'overfishing', 'plastic_pollution'], observations: 38, lat: 22.45, lng: -89.68, description: 'Parque Nacional Arrecife Alacranes. Único atolón coralino del Golfo de México. ~140 km al norte de Progreso. Refugio crítico para tortugas y aves marinas.', hero: '/images/reefs/alacranes.jpg', imageCredit: 'CONANP' },
  { id: 10, name: 'Huatulco', state: 'Oaxaca', ocean: 'pacific', region: 'Pacífico sur mexicano', benthicClasses: ['coral_algae', 'rock', 'sand'], geomorphicClasses: ['fringing', 'patch_reef'], area: 11891, depthRange: [1, 25], protection: 'anp_federal', status: 'warning', liveCoralCover: 19, bleachingAlert: 'warning', speciesRichness: 14, threats: ['thermal_stress', 'tourism_pressure', 'sedimentation'], observations: 54, lat: 15.72, lng: -96.13, description: 'Parque Nacional Huatulco. Comunidades coralinas en bahías protegidas (La Entrega, Cacaluta, San Agustín). Domina Pocillopora, con presión turística creciente.', hero: '/images/reefs/huatulco.jpg', imageCredit: 'CONANP' },
  { id: 11, name: 'Isla Contoy', state: 'Quintana Roo', ocean: 'caribbean', region: 'Sistema Arrecifal Mesoamericano (SAM)', benthicClasses: ['seagrass', 'sand', 'coral_algae'], geomorphicClasses: ['lagoon', 'fringing'], area: 5126, depthRange: [0, 20], protection: 'anp_federal', status: 'watch', liveCoralCover: 21, bleachingAlert: 'watch', speciesRichness: 19, threats: ['tourism_pressure', 'sargassum'], observations: 31, lat: 21.47, lng: -86.79, description: 'Parque Nacional Isla Contoy. Frente al norte del Caribe mexicano, refugio de aves y zona de agregación del tiburón ballena. Acceso turístico restringido.', hero: '/images/reefs/contoy.jpg', imageCredit: 'CONANP' },
  { id: 12, name: 'Isla Cerralvo / Espíritu Santo', state: 'Baja California Sur', ocean: 'pacific', region: 'Golfo de California', benthicClasses: ['rock', 'coral_algae'], geomorphicClasses: ['fringing', 'patch_reef'], area: 48655, depthRange: [3, 40], protection: 'anp_federal', status: 'healthy', liveCoralCover: 28, bleachingAlert: 'no_stress', speciesRichness: 8, threats: ['thermal_stress', 'tourism_pressure'], observations: 44, lat: 24.50, lng: -110.36, description: 'Parque Nacional Zona Marina Archipiélago de Espíritu Santo. Patrimonio Mundial UNESCO. Comunidades coralinas relictas dominadas por Pocillopora y Porites en muros rocosos.', hero: '/images/reefs/espiritu-santo.jpg', imageCredit: 'UNESCO / CONANP' },
];

const CONTRIBUTORS = [
  { id: 1, displayName: 'Dra. Adriana Reyes', handle: 'adriana_reyes', role: 'researcher', affiliation: 'CINVESTAV Mérida', state: 'Yucatán', joinedAt: '2024-03-15', tier: 'coral', reputationScore: 1245, validatedContributions: 187, rejectedContributions: 4, acceptanceRate: 0.979, averageQuality: 92, consecutiveMonthsActive: 14, badges: [{ id: 'top1', label: 'Top 1%', icon: 'lucide:crown' }], publicProfile: true, verified: true },
  { id: 2, displayName: 'Coop. Pesquera Vigía Chico', handle: 'vigiachico', role: 'fisher', affiliation: 'Vigía Chico, Quintana Roo', state: 'Quintana Roo', joinedAt: '2024-06-01', tier: 'platinum', reputationScore: 812, validatedContributions: 96, rejectedContributions: 8, acceptanceRate: 0.923, averageQuality: 86, consecutiveMonthsActive: 8, badges: [{ id: 'community', label: 'Comunidad' }], publicProfile: true, verified: true },
  { id: 3, displayName: 'Carlos Méndez', handle: 'carlos_diver', role: 'diver', affiliation: 'Cozumel Dive Pros', state: 'Quintana Roo', joinedAt: '2024-08-12', tier: 'gold', reputationScore: 612, validatedContributions: 71, rejectedContributions: 6, acceptanceRate: 0.922, averageQuality: 81, consecutiveMonthsActive: 6, badges: [], publicProfile: true, verified: false },
  { id: 4, displayName: 'CONANP Veracruz', handle: 'conanp_pnsav', role: 'government', affiliation: 'CONANP — PNSAV', state: 'Veracruz', joinedAt: '2024-04-20', tier: 'platinum', reputationScore: 905, validatedContributions: 112, rejectedContributions: 3, acceptanceRate: 0.974, averageQuality: 90, consecutiveMonthsActive: 12, badges: [{ id: 'institution', label: 'Institución verificada' }], publicProfile: true, verified: true },
  { id: 5, displayName: 'Mariana Solís', handle: 'mari_solis', role: 'student', affiliation: 'UAM-X — Posgrado', state: 'Oaxaca', joinedAt: '2025-01-08', tier: 'silver', reputationScore: 298, validatedContributions: 41, rejectedContributions: 9, acceptanceRate: 0.82, averageQuality: 73, consecutiveMonthsActive: 4, badges: [], publicProfile: true, verified: false },
  { id: 6, displayName: 'Tour Operador Cabo Pulmo', handle: 'cabopulmo_tours', role: 'tour_operator', affiliation: 'Cabo Pulmo', state: 'Baja California Sur', joinedAt: '2024-11-02', tier: 'gold', reputationScore: 532, validatedContributions: 58, rejectedContributions: 5, acceptanceRate: 0.92, averageQuality: 79, consecutiveMonthsActive: 5, badges: [], publicProfile: true, verified: true },
  { id: 7, displayName: 'Iván Pacheco', handle: 'ivan_p', role: 'citizen', state: 'Quintana Roo', joinedAt: '2025-02-14', tier: 'bronze', reputationScore: 88, validatedContributions: 12, rejectedContributions: 4, acceptanceRate: 0.75, averageQuality: 64, consecutiveMonthsActive: 2, badges: [], publicProfile: true, verified: false },
  { id: 8, displayName: 'Healthy Reefs Initiative MX', handle: 'hri_mx', role: 'ngo', affiliation: 'Healthy Reefs Initiative', state: 'Quintana Roo', joinedAt: '2024-02-01', tier: 'coral', reputationScore: 1410, validatedContributions: 213, rejectedContributions: 2, acceptanceRate: 0.991, averageQuality: 94, consecutiveMonthsActive: 15, badges: [{ id: 'ngo', label: 'ONG verificada' }], publicProfile: true, verified: true },
];

const CONFLICTS = [
  { id: 1, title: 'Anclaje de cruceros y daño coralino en Cozumel', summary: 'Cruceros con capacidad de 6,000+ pasajeros generan presión sobre arrecifes someros y bancos coralinos del muelle Punta Langosta.', fullStory: 'El crecimiento exponencial del turismo de cruceros en Cozumel desde 2010 ha incrementado el daño físico por anclas, descargas de aguas grises y derrames ocasionales. Estudios de CONANP documentan reducción del 23% en cobertura coralina en zonas de fondeo.', reefIds: [2], state: 'Quintana Roo', threats: ['cruise_anchoring', 'tourism_pressure', 'nutrient_pollution'], intensity: 'high', status: 'ongoing', affectedCommunities: ['Comunidad maya de San Miguel', 'Cooperativas de buceo locales'], affectedSpecies: ['Acropora palmata', 'Diploria strigosa'], startedAt: '2018-06-01', drivers: ['Líneas navieras (Carnival, Royal Caribbean)', 'FONATUR', 'Concesiones de muelles'], resistance: ['Cooperativa de Buceo Cozumel', 'CONANP', 'Healthy Reefs Initiative'], legalActions: ['Amparo 412/2023 vs ampliación de muelle Punta Langosta'], mediaUrls: ['https://example.com/news1'], contributorId: 8 },
  { id: 2, title: 'Tren Maya y sedimentos en arrecifes del Caribe sur', summary: 'Las obras del Tren Maya tramo 5 generan sedimentos que llegan al SAM vía cenotes y ríos subterráneos.', fullStory: 'Estudios independientes documentan turbidez elevada en arrecifes de Xcalak y Mahahual coincidente con obras del tramo 5. Geólogos advierten que el sistema kárstico transporta sedimentos directamente al mar.', reefIds: [5, 1], state: 'Quintana Roo', threats: ['sedimentation', 'coastal_development'], intensity: 'critical', status: 'ongoing', affectedCommunities: ['Comunidades mayas', 'Pescadores cooperativados'], affectedSpecies: ['Orbicella faveolata', 'Acropora cervicornis'], startedAt: '2022-01-15', drivers: ['FONATUR', 'SEDATU', 'Constructoras federales'], resistance: ['Cenotes Urbanos', 'Sélvame del Tren', 'CEMDA'], legalActions: ['Amparo colectivo 1102/2022', 'Suspensión definitiva (revertida)'], mediaUrls: [], contributorId: 8 },
  { id: 3, title: 'Sobrepesca de mero en Banco Chinchorro', summary: 'La pesca furtiva del mero rojo (Epinephelus morio) durante la temporada de agregación reproductiva amenaza la viabilidad poblacional.', fullStory: 'Reportes de CONAPESCA documentan capturas furtivas en zonas núcleo de la Reserva de la Biosfera durante enero-marzo, periodo crítico para la reproducción del mero rojo.', reefIds: [3], state: 'Quintana Roo', threats: ['overfishing', 'destructive_fishing'], intensity: 'high', status: 'ongoing', affectedCommunities: ['Cooperativa Vigía Chico', 'Cooperativa Andrés Quintana Roo'], affectedSpecies: ['Epinephelus morio'], startedAt: '2020-01-01', drivers: ['Pescadores furtivos', 'Mercado negro'], resistance: ['Cooperativa Vigía Chico', 'CONANP', 'Marina'], mediaUrls: [], contributorId: 2 },
  { id: 4, title: 'Aguas residuales y arrecifes de Huatulco', summary: 'Crecimiento hotelero rebasa la capacidad de tratamiento; descargas afectan bahías Cacaluta y San Agustín.', fullStory: 'El crecimiento de complejos turísticos en Huatulco ha excedido la capacidad de las plantas de tratamiento municipales, generando descargas con elevado contenido de nutrientes que provocan blanqueamiento por estrés osmótico.', reefIds: [10], state: 'Oaxaca', threats: ['nutrient_pollution', 'tourism_pressure'], intensity: 'medium', status: 'ongoing', affectedCommunities: ['Comunidades de Santa María Huatulco'], startedAt: '2019-05-01', drivers: ['Cadenas hoteleras', 'FONATUR'], resistance: ['CONANP Huatulco', 'Comités de cuenca'], mediaUrls: [], contributorId: 4 },
  { id: 5, title: 'Sargazo masivo en el Caribe mexicano', summary: 'Arribazones masivos de sargazo desde 2015 generan hipoxia en lagunas arrecifales y mortalidad de coral.', fullStory: 'El sargazo en descomposición consume oxígeno disuelto y libera ácido sulfhídrico, afectando críticamente las lagunas arrecifales de Puerto Morelos, Akumal y Mahahual.', reefIds: [1, 5, 11], state: 'Quintana Roo', threats: ['sargassum'], intensity: 'high', status: 'ongoing', affectedCommunities: ['Hoteleros', 'Pescadores', 'Comunidades costeras'], startedAt: '2015-04-01', drivers: ['Cambio climático', 'Eutrofización del Atlántico'], resistance: ['SEMAR', 'CONANP', 'Iniciativa privada hotelera'], mediaUrls: [], contributorId: 1 },
  { id: 6, title: 'SCTLD: enfermedad de pérdida de tejido coralino', summary: 'La enfermedad SCTLD ha matado >50% de algunas especies coralinas en el SAM desde 2018.', fullStory: 'La Stony Coral Tissue Loss Disease llegó al Caribe mexicano en 2018 y se ha propagado por todo el SAM. Afecta a más de 25 especies de coral y tiene tasas de mortalidad >70% en colonias infectadas.', reefIds: [1, 2, 3, 5], state: 'Quintana Roo', threats: ['disease_outbreak'], intensity: 'critical', status: 'ongoing', affectedSpecies: ['Pseudodiploria strigosa', 'Colpophyllia natans', 'Dichocoenia stokesii'], startedAt: '2018-07-01', drivers: ['Origen incierto (probablemente aguas de lastre)'], resistance: ['CONANP', 'Healthy Reefs Initiative', 'Universidades'], mediaUrls: [], contributorId: 8 },
];

export async function seedArrecifes() {
  const reefRepo = AppDataSource.getRepository(ObsReef);
  const contributorRepo = AppDataSource.getRepository(ObsContributor);
  const conflictRepo = AppDataSource.getRepository(ObsConflict);

  // Reefs
  for (const r of REEFS) {
    const existing = await reefRepo.findOne({ where: { id: r.id } });
    const data: any = { ...r, depthRange: r.depthRange as any };
    if (existing) {
      Object.assign(existing, data);
      await reefRepo.save(existing);
    } else {
      await reefRepo.save(reefRepo.create(data));
    }
  }

  // Contributors
  for (const c of CONTRIBUTORS) {
    const existing = await contributorRepo.findOne({ where: { id: c.id } });
    if (existing) {
      Object.assign(existing, c);
      await contributorRepo.save(existing);
    } else {
      await contributorRepo.save(contributorRepo.create(c as any));
    }
  }

  // Conflicts
  for (const k of CONFLICTS) {
    const existing = await conflictRepo.findOne({ where: { id: k.id } });
    if (existing) {
      Object.assign(existing, k);
      await conflictRepo.save(existing);
    } else {
      await conflictRepo.save(conflictRepo.create(k as any));
    }
  }

  console.log(`✅ Seeded arrecifes: ${REEFS.length} reefs, ${CONTRIBUTORS.length} contributors, ${CONFLICTS.length} conflicts`);
}
